Adfluence/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db  # means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user
from functools import wraps
from flask import abort


views = Blueprint("views", __name__)


def role_required(role):
    def decorator(f):
        @wraps(f)
        def decorated_function(*args, **kwargs):
            if current_user.role != role:
                abort(403)
            return f(*args, **kwargs)

        return decorated_function

    return decorator


@views.route("/", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        role = request.form.get("role")

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                if (
                    user.role == role
                ):  # Check if the user role matches the selected role
                    login_user(user, remember=True)
                    flash("Logged in successfully!", category="success")
                    if role == "Admin":
                        return redirect(url_for("admin.dashboard"))
                    elif role == "Sponsor":
                        return redirect(url_for("sponsor.dashboard"))
                    elif role == "Influencer":
                        return redirect(url_for("influencer.dashboard"))
                else:
                    flash(
                        "Incorrect role selected. Please check your role.",
                        category="error",
                    )
            else:
                flash("Incorrect password, try again.", category="error")
        else:
            flash("Email does not exist.", category="error")

    return render_template("login.html", user=current_user)


@views.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("views.login"))


@views.route("/sign-up", methods=["GET", "POST"])
def sign_up():
    if request.method == "POST":
        email = request.form.get("email")
        name = request.form.get("firstName")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")
        role = request.form.get("role")
        niche = request.form.get("niche")

        user = User.query.filter_by(email=email).first()
        if user:
            flash("Email already exists.", category="error")
        elif len(email) < 4:
            flash("Email must be greater than 3 characters.", category="error")
        elif len(name) < 2:
            flash("First name must be greater than 1 character.", category="error")
        elif password1 != password2:
            flash("Passwords don't match.", category="error")
        elif len(password1) < 7:
            flash("Password must be at least 7 characters.", category="error")
        else:
            new_user = User(
                email=email,
                role=role,
                name=name,
                niche=niche,
                password=generate_password_hash(password1),
            )
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash("Account created!", category="success")
            return redirect(url_for("views.login"))

    return render_template("sign_up.html", user=current_user)

Adfluence/templates/Influencer/Bookmarks.html
{% extends "base.html" %} {% block head %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='src/influencer_css/bookmarks.css') }}"
/>
{% endblock %} {% block content %}
<div class="container">
  <nav>
    <div class="nav-1">
      <a href="{{ url_for('influencer.dashboard') }}" class="logo view">
        AD <br />
        FL
      </a>
      <a href="{{ url_for('views.logout') }}" class="view">logout</a>
    </div>
    <div class="nav-2">
      <p class="menu-button">the</p>
      <p class="x">v</p>
      <p class="menu-button">dashboard</p>
    </div>
    <div class="nav-3">
      <a href="{{ url_for('influencer.viewCampaigns') }}" class="create view">
        find <ion-icon name="arrow-forward-sharp"></ion-icon> <br />
        campaigns
      </a>
      <a
        href="{{ url_for('influencer.activeCampaigns') }}"
        class="pattern-2 view"
      >
        active<br />
        campaigns
      </a>
    </div>
  </nav>
  <div class="content-wrapper">
    <div class="col-1 col">
      <div class="header">
        <h1>Bookmarked Campaigns</h1>
      </div>
      <div class="numbers">
        <p>xoxo</p>
        <div class="hr"></div>
        <p>xoxo</p>
      </div>
      <div class="table-wrapper">
        <table class="first-table">
          <thead>
            <tr>
              <th>Name of Sponsor</th>
              <th>Start Date</th>
              <th>End Date</th>
              <th>Budget</th>
              <th>Campaign description</th>
              <th class="link"></th>
              <th class="link"></th>
              <th class="link"></th>
            </tr>
          </thead>
          <tbody>
            {% for campaign in bookmarked_campaigns %} {% if influencer.flagged
            == False %}

            <tr>
              <td>{{ campaign.name }}</td>
              <td>{{ campaign.start_date.strftime('%Y-%m-%d') }}</td>
              <td>{{ campaign.end_date.strftime('%Y-%m-%d') }}</td>
              <td>Rs. {{ campaign.budget }}</td>
              <td>{{ campaign.description }}</td>
              <td class="link view">
                <a
                  href="{{ url_for('influencer.viewCampaign', campaign_id=campaign.id) }}"
                  >View</a
                >
              </td>
              <td class="link view">
                <a
                  href="{{ url_for('influencer.create_ad_request', campaign_id=campaign.id)}}"
                  >Request</a
                >
              </td>
              <td class="link view">
                <form
                  action="{{ url_for('influencer.bookmark_campaign', campaign_id=campaign.id) }}"
                  method="post"
                  style="display: inline"
                >
                  {% if campaign.is_bookmarked %}
                  <button type="submit">
                    <svg
                      class="bookmark-icon"
                      fill="#000"
                      width="50"
                      height="50"
                      viewBox="0 0 1024.00 1024.00"
                      xmlns="http://www.w3.org/2000/svg"
                      stroke="#000"
                      stroke-width="0.01024"
                    >
                      <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                      <g
                        id="SVGRepo_tracerCarrier"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      ></g>
                      <g id="SVGRepo_iconCarrier">
                        <path
                          d="M665.6 768L512 614.4 358.4 768V256h307.2v512z"
                        ></path>
                      </g>
                    </svg>
                  </button>
                  {% else %}
                  <button type="submit">
                    <svg
                      class="bookmark-icon"
                      fill="#000"
                      width="50"
                      height="50"
                      viewBox="0 0 1024 1024"
                      xmlns="http://www.w3.org/2000/svg"
                      stroke="#000"
                    >
                      <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                      <g
                        id="SVGRepo_tracerCarrier"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      ></g>
                      <g id="SVGRepo_iconCarrier">
                        <path
                          d="M665.6 768L512 614.4 358.4 768V256h307.2v512zM512 537.6L614.4 640V307.2H409.6V640L512 537.6z"
                        ></path>
                      </g>
                    </svg>
                  </button>
                  {% endif %}
                </form>
              </td>
            </tr>

            {% endif %} {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-2 col"></div>
  </div>
</div>

{% endblock %}

Adfluence/templates/Influencer/activeCampaigns.html
{% extends "base.html" %} {% block head %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='src/influencer_css/active_campaigns.css') }}"
/>
{% endblock %} {% block content %}

<div class="container">
  <nav>
    <div class="nav-1">
      <a href="{{ url_for('influencer.dashboard') }}" class="logo view">
        AD <br />
        FL
      </a>
      <a href="{{ url_for('views.logout') }}" class="view">logout</a>
    </div>
    <div class="nav-2">
      <p class="menu-button">the</p>
      <p class="x">v</p>
      <p class="menu-button">dashboard</p>
    </div>
    <div class="nav-3">
      <a href="{{ url_for('influencer.viewCampaigns') }}" class="view"
        >Find Campaigns</a
      >
      <p>
        <svg
          width="40"
          height="40"
          viewBox="0 0 24 24"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M10 3H8V5H6V7H8V5H10V7H12V9H10V11H8V13H6V15H4V13H2V15H4V17H6V15H8H10V17H12V19H10V21H12V19H14V17H12V15V13H14V11H16V13H18V15H20V13H22V11H20V13H18V11H16V9H18V5H14V7H12V5H10V3Z"
            fill="black"
          />
        </svg>
      </p>
    </div>
  </nav>

  <div class="content-wrapper">
    <div class="header-wrapper">
      <div class="header-1">
        <h1>Active campaigns</h1>
      </div>
      <div class="header-2">
        <div class="marquee">
          <span>
            <a href="{{ url_for('influencer.view_completed_requests')}}">
              Completed Requests &nbsp; Completed Requests &nbsp; Completed
              Requests &nbsp; Completed Requests &nbsp; Completed Requests
              &nbsp; Completed Requests &nbsp; Completed Requests &nbsp;
              Completed Requests &nbsp; Completed Requests &nbsp; Completed
              Requests &nbsp; Completed Requests &nbsp; Completed Requests
              &nbsp; Completed Requests &nbsp;
            </a>
          </span>
        </div>
      </div>
    </div>
    <div class="table-wrapper">
      <table class="first-table">
        <thead>
          <th>Request Type</th>
          <th>Campaign</th>
          <th>Sponsor</th>
          <th>Payment Amount</th>
          <th>Requirements</th>
          <th>Message</th>
          <th class="link"></th>
        </thead>
        <tbody>
          {% for request in ad_requests + campaign_requests %}{% if
          request.request.status == "Accepted" %}

          <tr>
            <td>{{ request.request_type }}</td>
            <td>{{ request.campaign_name }}</td>
            <td>{{ request.user_name }}</td>
            <td>{{ request.request.payment_amount }}</td>
            <td>{{ request.request.requirements }}</td>
            <td>{{ request.request.messages }}</td>
            <td>
              <form
                method="POST"
                action="{{url_for('influencer.mark_completed', ad_request_id=request.request.id)}}"
              >
                <input
                  type="text"
                  name="request_type"
                  value="{{ request.request_type }}"
                  hidden
                />
                <button class="view link" type="submit">Mark Completed</button>
              </form>
            </td>
            {% endif %} {% endfor %}
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}

Adfluence/templates/Influencer/addInfluencer.html
{% extends "base.html" %} {% block head %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='src/influencer_css/add_influencer.css') }}"
/>
{% endblock %} {% block content %}
<div class="container">
  <nav>
    <div class="nav-1">
      <p class="logo view">
        AD <br />
        FL
      </p>
      <a href="{{ url_for('views.logout') }}" class="view">logout</a>
    </div>
    <div class="nav-2">
      <p class="menu-button">Sign-up</p>
      <p class="x">x</p>
      <p class="menu-button">page</p>
    </div>
    <div class="nav-3"></div>
  </nav>

  <div class="form-wrapper">
    <form
      action="{{ url_for('influencer.addInfluencer') }}"
      method="POST"
      enctype="multipart/form-data"
    >
      <div class="content-wrapper">
        <div class="col col-1">
          <div class="header">
            <h1>Sign-up as an Influencer</h1>
          </div>
          <div class="form-fields">
            <input
              type="hidden"
              id="name"
              name="name"
              value="{{ current_user.name }}"
              required
            />
            <input
              type="hidden"
              id="email"
              name="email"
              value="{{ current_user.email }}"
            />
            <div class="form-field">
              <label class="cc-label" for="platform">Platform</label>
              <select name="platform" id="platform" class="cc-input">
                <option value="">Please select</option>
                <option value="Facebook">Facebook</option>
                <option value="Instagram">Instagram</option>
                <option value="Twitter">Twitter</option>
                <option value="LinkedIn">LinkedIn</option>
                <option value="Youtube">Youtube</option>
                <option value="Snapchat">Snapchat</option>
                <option value="TikTok">TikTok</option>
                <option value="Twitch">Twitch</option>
                <option value="Other">Other</option>
              </select>
            </div>
            <div class="form-field">
              <label class="cc-label" for="profile_picture"
                >Profile Picture:</label
              >
              <input
                type="file"
                id="profile_picture"
                name="profile_picture"
                class="cc-input"
              />
            </div>
            <div class="form-field">
              <label class="cc-label" for="niche">Niche:</label>
              <select id="niche" name="niche" class="cc-input">
                <option value="">Please select</option>
                <option value="Tech">Tech</option>
                <option value="Fashion and Beauty">Fashion and Beauty</option>
                <option value="Fitness and Wellness">
                  Fitness and Wellness
                </option>
                <option value="Travel">Travel</option>
                <option value="Food ">Food</option>
                <option value="Lifestyle">Lifestyle</option>
                <option value="Gaming">Gaming</option>
                <option value="Finance and Investing">
                  Finance and Investing
                </option>
                <option value="Entertainment and Pop Culture">
                  Entertainment and Pop Culture
                </option>
              </select>
            </div>
            <div class="form-field">
              <label class="cc-label" for="reach">Reach:</label>
              <input
                type="number"
                id="reach"
                name="reach"
                required
                class="cc-input"
              />
            </div>

            <input type="hidden" name="user_id" value="{{ current_user.id }}" />

            <label class="button-wrapper" for="submit-button">
              <button type="submit" id="submit-button" class="submit-btn">
                Add influencer
              </button>
              <ion-icon name="arrow-forward-sharp"></ion-icon>
            </label>
          </div>
        </div>
        <div class="col-2">
          <div class="circle">
            <div class="arrow arrow1">
              <svg
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 40 31"
              >
                <path
                  d="M32.7188 30.2092L25.6611 30.1823L29.01 13.9866L12.2259 29.4822C11.7383 29.9323 11.099 30.1823 10.4353 30.1823H0.350586L24.5691 7.7427L9.97643 7.72816L12.817 1.29864C13.0989 0.660689 13.7309 0.24938 14.4283 0.250001L34.8251 0.268164C37.6565 0.269449 39.7495 2.90594 39.1084 5.66374L34.4507 28.7968C34.2848 29.6208 33.5593 30.2124 32.7188 30.2092Z"
                  fill="#000"
                ></path>
              </svg>
            </div>
            <div class="arrow2">
              <svg
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 40 31"
              >
                <path
                  d="M32.7188 30.2092L25.6611 30.1823L29.01 13.9866L12.2259 29.4822C11.7383 29.9323 11.099 30.1823 10.4353 30.1823H0.350586L24.5691 7.7427L9.97643 7.72816L12.817 1.29864C13.0989 0.660689 13.7309 0.24938 14.4283 0.250001L34.8251 0.268164C37.6565 0.269449 39.7495 2.90594 39.1084 5.66374L34.4507 28.7968C34.2848 29.6208 33.5593 30.2124 32.7188 30.2092Z"
                  fill="#000"
                ></path>
              </svg>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>

  {% endblock %}
</div>

Adfluence/templates/Influencer/create_ad_request.html
{% extends "base.html" %} {% block head %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='src/influencer_css/create_ad_request.css') }}"
/>

{% endblock %} {% block content %}

<div class="container">
  <nav>
    <div class="nav-1">
      <a href="{{ url_for('influencer.dashboard') }}" class="logo view">
        AD <br />
        FL
      </a>
      <a href="{{ url_for('views.logout') }}" class="view">logout</a>
    </div>
    <div class="nav-2">
      <p class="menu-button">the</p>
      <p class="x">v</p>
      <p class="menu-button">dashboard</p>
    </div>
    <div class="nav-3">
      
      <a href="{{ url_for('influencer.viewCampaigns') }}" class="view"
        >Find Campaigns</a
      >
    </div>
  </nav>
  <div class="form-wrapper">
    <form
      action="{{ url_for('influencer.create_ad_request', campaign_id=campaign.id) }}"
      method="POST"
    >
      <div class="content-wrapper">
        <div class="col col-1">
          <div class="header-ad header">
            <h1>Create ad Request for {{ campaign.name }}</h1>
          </div>
          <div class="numbers">
            <p>xoxo</p>
            <div class="hr"></div>
            <p>xoxo</p>
          </div>
          <div class="form-fields">
            <div>
              <label class="cc-label" for="requirements">Task: </label>
              <div class="form-field">
                <input
                  class="cc-input"
                  id="requirements"
                  name="requirements"
                  required
                />
              </div>
            </div>

            <div>
              <label class="cc-label" for="messages">Message</label>

              <div class="form-field">
                <input
                  class="cc-input"
                  id="messages"
                  name="messages"
                  required
                />
              </div>
            </div>

            <div>
              <div>
                <label class="cc-label" for="payment_amount"
                  >Request Amount</label
                >

                <div class="form-field">
                  <input
                    type="number"
                    class="cc-input"
                    id="payment_amount"
                    name="payment_amount"
                    step="1"
                    required
                  />
                </div>
                <div>
                  <label class="button-wrapper" for="submit-button">
                    <button type="submit" id="submit-button" class="submit-btn">
                      Create ad request
                    </button>
                    <ion-icon name="arrow-forward-sharp"></ion-icon>
                  </label>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-2">
          <div class="circle">
            <div class="arrow arrow1">
              <svg
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 40 31"
              >
                <path
                  d="M32.7188 30.2092L25.6611 30.1823L29.01 13.9866L12.2259 29.4822C11.7383 29.9323 11.099 30.1823 10.4353 30.1823H0.350586L24.5691 7.7427L9.97643 7.72816L12.817 1.29864C13.0989 0.660689 13.7309 0.24938 14.4283 0.250001L34.8251 0.268164C37.6565 0.269449 39.7495 2.90594 39.1084 5.66374L34.4507 28.7968C34.2848 29.6208 33.5593 30.2124 32.7188 30.2092Z"
                  fill="#000"
                ></path>
              </svg>
            </div>
            <div class="arrow2">
              <svg
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 40 31"
              >
                <path
                  d="M32.7188 30.2092L25.6611 30.1823L29.01 13.9866L12.2259 29.4822C11.7383 29.9323 11.099 30.1823 10.4353 30.1823H0.350586L24.5691 7.7427L9.97643 7.72816L12.817 1.29864C13.0989 0.660689 13.7309 0.24938 14.4283 0.250001L34.8251 0.268164C37.6565 0.269449 39.7495 2.90594 39.1084 5.66374L34.4507 28.7968C34.2848 29.6208 33.5593 30.2124 32.7188 30.2092Z"
                  fill="#000"
                ></path>
              </svg>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

Adfluence/templates/Influencer/dashboard.html
{% extends "base.html" %} {% block head %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='src/influencer_css/dashboard.css') }}"
/>
{% endblock %} {% block content %}

<div class="container">
  {% if not current_user.influencers %}
  <div class="text-center cyp-wrapper">
    <a href="{{ url_for('influencer.addInfluencer') }}" class="cyp-btn btn-sec">
      <span class="text">COMPLETE YOUR PROFILE</span>
    </a>
    <svg
      width="60"
      height="60"
      viewBox="0 0 60 60"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g style="mix-blend-mode: multiply">
        <path d="M0 0H11.25V3.75H7.5V7.5H3.75V11.25H0V0Z" fill="white" />
        <path
          d="M11.25 0H22.5V3.75H26.25V7.5H33.75V3.75H37.5V0H48.75V3.75H52.5V7.5H56.25V11.25H60V22.5H56.25V30H52.5V37.5H48.75V41.25H45V45H41.25V48.75H37.5V52.5H33.75V56.25H30V52.5H26.25V48.75H22.5V45H18.75V41.25H15V37.5H11.25V33.75H7.5V30H3.75V22.5H0V11.25H3.75V7.5H7.5V3.75H11.25V0Z"
          fill="#384243"
        />
        <path d="M22.5 0H37.5V3.75H33.75V7.5H26.25V3.75H22.5V0Z" fill="white" />
        <path d="M48.75 0H60V11.25H56.25V7.5H52.5V3.75H48.75V0Z" fill="white" />
        <path
          d="M0 22.5H3.75V30H7.5V33.75H11.25V37.5H15V41.25H18.75V45H22.5V48.75H26.25V52.5H30V56.25H33.75V52.5H37.5V48.75H41.25V45H45V41.25H48.75V37.5H52.5V30H56.25V22.5H60V37.5H56.25V45H52.5V48.75H45V52.5H52.5V48.75H56.25V45H60V52.5H56.25V56.25H48.75V60H15V56.25H7.5V52.5H3.75V48.75H0V22.5Z"
          fill="white"
        />
        <path d="M3.75 37.5H7.5V45H3.75V37.5Z" fill="#384243" />
        <path d="M56.25 37.5H60V45H56.25V37.5Z" fill="#384243" />
        <path d="M7.5 45H11.25V48.75H7.5V45Z" fill="#384243" />
        <path d="M52.5 45H56.25V48.75H52.5V45Z" fill="#384243" />
        <path d="M0 48.75H3.75V52.5H0V48.75Z" fill="#384243" />
        <path d="M11.25 48.75H18.75V52.5H11.25V48.75Z" fill="#384243" />
        <path d="M45 48.75H52.5V52.5H45V48.75Z" fill="#384243" />
        <path d="M0 52.5H3.75V56.25H7.5V60H0V52.5Z" fill="white" />
        <path d="M3.75 52.5H7.5V56.25H3.75V52.5Z" fill="#384243" />
        <path d="M56.25 52.5H60V56.25H56.25V52.5Z" fill="#384243" />
        <path d="M7.5 56.25H15V60H7.5V56.25Z" fill="#384243" />
        <path d="M48.75 56.25H56.25V60H48.75V56.25Z" fill="#384243" />
        <path d="M56.25 56.25H60V60H56.25V56.25Z" fill="white" />
      </g>
    </svg>
  </div>

  {% endif %} {% if influencer %}
  <nav>
    <div class="nav-1">
      <p class="logo view">
        AD <br />
        FL
      </p>
      <a href="{{ url_for('views.logout') }}" class="view">logout</a>
    </div>
    {% if influencer.flagged == True %}
    <div class="nav-2 flagged">
      <p class="text-center">You have been flagged by admin</p>
    </div>
    {% else%}
    <div class="nav-2">
      <p class="menu-button">the</p>
      <p class="x">x</p>
      <p class="menu-button">dashboard</p>
    </div>
    {% endif %}

    <div class="nav-3">
      <a href="{{ url_for('influencer.viewCampaigns') }}" class="create view">
        Find <ion-icon name="arrow-forward-sharp"></ion-icon> <br />
        campaigns
      </a>
      <a
        href="{{ url_for('influencer.activeCampaigns') }}"
        class="pattern-2 view"
      >
        active <br />
        campaigns
      </a>
    </div>
  </nav>
  <div class="content-wrapper">
    <div class="col-1 col">
      <div class="pfp-wrapper">
        <img
          src="{{ url_for('static', filename='uploads/' + influencer.profile_picture) }}"
          alt="{{ influencer.name }}'s profile picture"
          class="pfp"
        />
      </div>
      <div class="name">{{ influencer.name }}</div>
      <div class="table-wrapper">
        <table class="first-table">
          <thead>
            <tr>
              <th>Niche</th>
              <th style="width: 80px">Reach</th>
              <th style="width: 80px">Rating</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{ influencer.niche }}</td>
              <td style="width: 80px">{{ influencer.reach }}</td>
              <td style="width: 80px">{{average_rating}}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <a
        href="{{ url_for('influencer.editInfluencer', influencer_id=influencer.id) }}"
      >
        <img class="arrow" src="../../static/thinArrow.png" alt="" />
      </a>

      <div class="more-info">
        <table>
          <tr>
            <th>Email:</th>
            <td>{{ influencer.email }}</td>
          </tr>
          <tr>
            <th>Platform:</th>
            <td>{{ influencer.platform }}</td>
          </tr>
          <tr>
            <th>Reach:</th>
            <td>{{ influencer.reach }}</td>
          </tr>
          <tr>
            <th>Earnings:</th>
            <td>Rs. {{ influencer.bank_account_balance }}</td>
          </tr>
        </table>
      </div>
    </div>
    <div class="col-2 col">
      <h1>Pending Requests</h1>
      <div class="table-wrapper-2 m-xl">
        <table class="second-table">
          <thead>
            <tr>
              <th>Campaign</th>
              <th>Sponsor</th>
              <th>Payment Amount</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for ad_request_details in ad_requests %} {% if
            ad_request_details.ad_request.status == "Pending" %}

            <tr>
              <td>{{ ad_request_details.campaign_name }}</td>
              <td>{{ ad_request_details.user_name }}</td>
              <td>{{ ad_request_details.ad_request.payment_amount }}</td>
              <td>
                <a
                  class="link view"
                  href="{{ url_for('influencer.viewRequest', ad_request_id=ad_request_details.ad_request.id) }}"
                  >View</a
                >
              </td>
              <td>
                <form
                  action="{{ url_for('influencer.accept_ad_request', ad_request_id=ad_request_details.ad_request.id) }}"
                  method="post"
                >
                  <button class="link approve" type="submit">Approve</button>
                </form>
              </td>
              <td>
                <form
                  action="{{ url_for('influencer.reject_ad_request', ad_request_id=ad_request_details.ad_request.id) }}"
                  method="post"
                >
                  <button class="link danger" type="submit">Reject</button>
                </form>
              </td>
              {% endif %} {% endfor %}
            </tr>
          </tbody>
        </table>
      </div>

      <h1>Sent Requests</h1>
      <div class="table-wrapper-2">
        <table class="second-table">
          <thead>
            <tr>
              <th>Campaign</th>
              <th>Requirements</th>
              <th>Message</th>
              <th>Requested Amount</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for campaignRequest in campaign_requests %} {% if
            campaignRequest.campaign_request.status == "Pending" %}

            <tr>
              <td>{{campaignRequest.campaign_name}}</td>
              <td>{{ campaignRequest.campaign_request.requirements }}</td>
              <td>{{ campaignRequest.campaign_request.messages }}</td>
              <td>{{ campaignRequest.campaign_request.payment_amount }}</td>
              <td>
                <a
                  href="{{ url_for('influencer.edit_campaign_request', campaign_request_id=campaignRequest.campaign_request.id)}}"
                  class="link view"
                  >Edit</a
                >
              </td>
              <td>
                <form
                  action="{{ url_for('influencer.delete_campaign_request', campaign_request_id=campaignRequest.campaign_request.id) }}"
                  method="POST"
                  onsubmit="return confirm('Are you sure you want to delete the request?');"
                >
                  <button class="link danger" type="submit">Delete</button>
                </form>
              </td>
              {% endif %} {% endfor %}
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endif %} {% endblock %}